//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComoCrossCountry
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicContent
    {
        public int ID { get; set; }
        public string Content { get; set; }
        public string SectionName { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
