//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComoCrossCountry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Race
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string FormattedResults { get; set; }
        public Nullable<int> MeetId { get; set; }
    
        public virtual Meet Meet { get; set; }
    }
}
